"""Constants."""
# Device Types (https://developer.nuki.io/page/nuki-bridge-http-api-1-13/4#heading--device-types)
DEVICE_TYPE_SMARTLOCK = 0
DEVICE_TYPE_OPENER = 2
DEVICE_TYPE_SMARTDOOR = 3
DEVICE_TYPE_SMARTLOCK3 = 4

# Modes (https://developer.nuki.io/page/nuki-bridge-http-api-1-13/4#heading--modes)
## SmartLock
MODE_LOCK_DOOR = 2

## Opener
MODE_OPENER_DOOR = 2
MODE_OPENER_CONTINUOUS = 3

# Lock states (https://developer.nuki.io/page/nuki-bridge-http-api-1-13/4#heading--lock-states)
## SmartLock
STATE_LOCK_UNCALIBRATED = 0
STATE_LOCK_LOCKED = 1
STATE_LOCK_UNLOCKING = 2
STATE_LOCK_UNLOCKED = 3
STATE_LOCK_LOCKING = 4
STATE_LOCK_UNLATCHED = 5
STATE_LOCK_UNLOCKED_LOCK_N_GO = 6
STATE_LOCK_UNPLATCHING = 7
STATE_LOCK_MOTOR_BLOCKED = 254
STATE_LOCK_UNDEFINED = 255

## Opener
STATE_OPENER_UNTRAINED = 0
STATE_OPENER_ONLINE = 1
STATE_OPENER_RTO_ACTIVE = 3
STATE_OPENER_OPEN = 5
STATE_OPENER_OPENING = 7
STATE_OPENER_UNDEFINED = 255

# Lock actions (https://developer.nuki.io/page/nuki-bridge-http-api-1-13/4#heading--lock-actions)
## SmartLock
ACTION_LOCK_UNLOCK = 1
ACTION_LOCK_LOCK = 2
ACTION_LOCK_UNLATCH = 3
ACTION_LOCK_LOCK_N_GO = 4
ACTION_LOCK_LOCK_N_GO_WITH_UNLATCH = 5

## Opener
ACTION_OPENER_ACTIVATE_RTO = 1
ACTION_OPENER_DEACTIVATE_RTO = 2
ACTION_OPENER_ELECTRIC_STRIKE_ACTUATION = 3
ACTION_OPENER_ACTIVATE_CONTINUOUS_MODE = 4
ACTION_OPENER_DEACTIVATE_CONTINUOUS_MODE = 5

# Doorsensor states (https://developer.nuki.io/page/nuki-bridge-http-api-1-13/4#heading--doorsensor-states)
STATE_DOORSENSOR_DEACTIVATED = 1
STATE_DOORSENSOR_DOOR_CLOSED = 2
STATE_DOORSENSOR_DOOR_OPENED = 3
STATE_DOORSENSOR_DOOR_STATE_UNKNOWN = 4
STATE_DOORSENSOR_CALIBRATING = 5
STATE_DOORSENSOR_UNCALIBRATED = 16
STATE_DOORSENSOR_REMOVED = 240
STATE_DOORSENSOR_UNKNOWN = 255