name: Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - main

jobs:
  update_release_draft:
    # Disabled for now
    if: ${{ false }}

    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5.23.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}